Add:

#define ENABLE_DROP_EVENT
#ifdef ENABLE_DROP_EVENT
  #define ENABLE_DROP_EVENT_MAX_DIFFERENCE  30
#endif
#define ENABLE_MOONLIGHT_CHEST_DROP
#ifdef ENABLE_MOONLIGHT_CHEST_DROP
  #define MOONLIGHT_CHEST_DROP_VNUM 50011
  #define MOONLIGHT_CHEST_DROP_CHANCE 1
#endif
